### ISSUE TITLE
Example of the Readme is not working

### ISSUE THREAD

**Issue by eliot-dessennes** [noahlorinczcomi/MRBEE#1]
Hi, 

The mendelian randomization method you're providing seems really cool, and I wanted to try it. 

However, the example of the README is not working anymore. Maybe some entry of the function changed without actualizing it.

Thanks for you work, 
Best regards 
Eliot Dessennes

**Comment by noahlorinczcomi** [comment]
Hi Eliot,

Thank you for alerting us to this, and I apologize that it does not work according to the README.

We have since changed some parts of the package to make it easier to use. The README has been updated with the new tutorial.

Thanks,
Noah

**Comment by eliot-dessennes** [comment]
Hi Noah, 

I managed to try your method, diving a little bit into the code. 

Thanks for your reply, and your work ! 

Best regards, 
Eliot 


De: "Noah Lorincz-Comi" ***@***.***> 
À: "noahlorinczcomi/MRBEE" ***@***.***> 
Cc: "Eliot DESSENNES" ***@***.***>, "Author" ***@***.***> 
Envoyé: Samedi 22 Juillet 2023 04:54:29 
Objet: Re: [noahlorinczcomi/MRBEE] Example of the Readme is not working (Issue #1) 





Hi Eliot, 

Thank you for alerting us to this, and I apologize that it does not work according to the README. 

We have since changed some parts of the package to make it easier to use. The README has been updated with the new tutorial. 

Thanks, 
Noah

**Comment by noahlorinczcomi** [comment]
Thanks, Eliot. Best of luck
