### ISSUE TITLE
NameError: name 'V' is not defined

### ISSUE THREAD

**Issue by Yask-Gupta** [noahlorinczcomi/MRBEE#2]
Dear Author,
I am trying to run MIRBEE on my own gwas summary stats but when i run genomePleio function i get this error.
Cell In[83], line 1
----> 1 gwp=genomePleio(BX,BY,BXSE,BYSE,R,est,V)

File G:\software\MRBEE\mrbeecmdfunctions.py:158, in genomePleio(BX, BY, BXSE, BYSE, cc, ests, Vests)
    156 UV_=numpy.row_stack((0,UV))
    157 # association testing
--> 158 chistat=((byi-bxi@est)**2)/(VV+est.T@UU_@est+bxi@V@bxi.T-2*(est.T@UV_))
    159 sp=1-stats.chi2.cdf(float(chistat),1)
    160 exposureP=float(1-stats.chi2.cdf(bxi[:,1:]@numpy.linalg.inv(UU)@bxi[:,1:].T,p)) # joint test for exposures

NameError: name 'V' is not defined
Thanks
Yask

**Comment by noahlorinczcomi** [comment]
Hi Yask,

Thank you very much for alerting me to this. The problem was on our end, where 'V' should have been 'Vests'. I have now fixed the issue and it should work for you if you re-download `mrbeecmd.py` and `mrbeecmdfunctions.py`.

I created and ran the following example to ensure the problem was fixed:
```R
# in working directory, generate data
set.seed(1)
gendata=function() {
  n=length(LETTERS)
  data.frame(
    SNP=LETTERS,
    beta=rnorm(n),
    se=rnorm(n),
    ea=sample(c('A','B'),n,replace=T)
  )
}
df1=gendata()
df2=gendata()
df3=gendata()
IVs=data.frame(SNP=sample(LETTERS,10))
wt=function(x,n) write.table(x,n,row.names=FALSE,quote=FALSE)
wt(df1,'outcome.txt')
wt(df2,'exposure1.txt')
wt(df3,'exposure2.txt')
wt(IVs,'IVs.txt')
```
Then gzip the GWAS data sets (I'm using WSL so I do it like this, otherwise you can do it within R using the system() command)
```unix
gzip outcome.txt exposure1.txt exposure2.txt
```
Then executing MRBEE (may need to change `python3` to `python` on your machine)
```unix
python3 mrbeecmd.py \
 -exposureGWAS exposure1.txt.gz,exposure2.txt.gz \
 -outcomeGWAS outcome.txt.gz \
 -IVs IVs.txt \
 -exposureSNP SNP,SNP\
 -outcomeSNP SNP \
 -exposureBETA beta,beta \
 -exposureSE se,se \
 -outcomeBETA beta \
 -outcomeSE se \
 -outcomeEffectAllele ea \
 -exposureEffectAllele ea,ea \
 -stdZ true \
 -genomewideSpleio true \
 -out results
```
which prints the following:
```unix
Getting things ready
Reading in outcome GWAS data
Reading in GWAS data for exposure 1
Reading in GWAS data for exposure 2
Harmonizing alleles
Calculating bias-correction terms
Performing MR
Using 10 candidate SNPs in MR
2 SNPs removed from MR because of horizontal pleiotropy, 8 SNPs remain
    Exposure       Est        SE         P
0  intercept  0.452946  0.936098  0.628481
1  Exposure0  0.619339  0.360265  0.085593
2  Exposure1 -0.046230  0.145313  0.750381
Performing genome-wide horizontal pleiotropy testing using Spleio
Saving results to results_<causal_estimates,MR_data,genomewide_Spleio>.csv
```
